treewide: AOSP fixes
usb: gadget: RIP Samsung MTP driver

* It simply doesn't work on AOSP, and never did.

Change-Id: Id42c091d45965037eca200041cd00de5ada8d275

input: touchscreen: sec_ts: Invert reported proximity values

* On stock higher value indicates closer proximity while on AOSP it is expected to be the other way around

Change-Id: Ib27d408f5e45dbd42b61bc37f0f3ef30e28157b9

drm: msm: sde: translate zpos property to fod property

Change-Id: I562e6738cd0b09e67b91a0d697d045c2f3984798

uapi: sde_drm: Define FOD_PRESSED_LAYER_ZORDER

Change-Id: I38638b97ec54d6c00f30fa77c51f19d141d43738

drm/msm/sde: Do not limit maximum for zpos property

We are going to use special high values for zpos property to map
them to fod property values. Allow userspace to pass such high
values.

Change-Id: I8cdb86f73337c2d929047f84712de02a960167ab

drm: sde: Increase sde stage to map zpos changes

* Another stage should be added, otherwise fingerprint payment won't work in some apps like Alipay and Jingdong.

Change-Id: I0dd347a9599ec45b129b8483051ad134ed6bc86c

drm: msm: dsi-staging: create empty attributes group

Change-Id: I9fe21356804e1fbd589cf4c155a722ad2ba8bcc8

drm: msm: dsi-staging: add get_main_display

Change-Id: I0e330858faea435bfa1c729b76fb1419ff791337

drm: msm: dsi-staging: add dsi_panel_get_backlight

Change-Id: I11a5408e2df139a056674d7db3de6c8e00fdbf69

drm: msm: implement fod handling

Change-Id: I30f1ebd041c429deccc64da2dcef34df9b3902c3

drm: msm: make Samsung HBM work

On stock ROM Samsung writes the brightness value for the finger mask to /sys/class/lcd/panel/mask_brightness and then turns on the mask layer. However we don't know how they actually turn it on. Therefore enable/disable the finger mask every time we write something to mask_brightness.

Change-Id: I60cba88324c93e41275b1bd0c7885a1715517ae5

drm: msm: dsi-staging: Update FOD dim lut table

Change-Id: Ic4e247affbb88e1cf257868105730e16a72be85b

input: keyboard: hall_ic: Report SW_LID instead of SW_FLIP

* Android expects SW_LID for lid events.

Change-Id: I70a77d6ce78da2b800eb5188428fa2697e0228d7

drivers: input: touchscreen: sec_ts: Add sysfs to track FOD

* pressed state /sys/class/sec/tsp/input/fod_pressed 0 -> not pressed 1 ->
 pressed.

Change-Id: I84eb8d990c3368f48f7f07d4a36b99c7601e5a8f

drm: msm: Properly dim the screen for HBM

This reverts commit 9428b78318615b4fff623c30a97fb694b6a9a77d.

Change-Id: If53b8eaff0291e36c869a676758ba385b894ac89

drm: msm: translate PCC to CSC

PCC cannot be applied per-plane, but CSC can. Translate PCC to CSC
to allow skipping it for some planes.

Change-Id: Icd8c7e528e260265a79129fd845004226e8cfdde

drm: msm: fix -Wincompatible-pointer-types error

../drivers/gpu/drm/msm/sde/sde_color_processing.c:892:9: error: incompatible pointer types returning 'unsigned char *' from a function with result type 'struct drm_msm_pcc *' [-Werror,-Wincompatible-pointer-types] return blob ? blob->data : NULL; ^~~~~~~~ 1 error generated.

Change-Id: I489d359ca49b59696f29f3d9615c5f275748719f

drm: msm: skip marking null blob changes as dirty

Change-Id: I69b8ba87b0428c36d08a76326f8dbb2c087da65a

drm: msm: optimize exclusion rects dirty marking

Change-Id: I0b0058c67a90a7eeb672813bd79a14080233a090

drm: msm: do not create virtual planes for VIG planes

Multirect virtual planes have an issue with CSC causing apparent
non-CSC flashes.
Without smart DMA, SDE doesn't register any multirect virtual planes.
This is a very hacky solution, that might cause some performance
defficits.

Change-Id: I00a87e4c211bdc9915c6124b527a32b8a3066445

drm: msm: ignore CSC config on FOD layer

FOD performance decreases if the color of the icon is not
exactly white, which happens when night light is enabled.
Skip CSC for the FOD layer.

Change-Id: I0c1bff985879bfab325c648c98e7a50679107833

battery: common: remove sec_vote calls

* They aren't neccessary for starting/stopping charging using batt_slate_mode and break the flashlight when slate mode is enabled.

Change-Id: I083a8371cc82c2ac9bce88bcc183dfee0975cf20

drm: msm: enable HBM alongside dimming

Change-Id: I000030bef5256423ff5e77bbcee177e1c1694123

input: touchscreen: sec_ts: Don't report KEY_BLACK_UI_GESTURE on FOD events

Change-Id: If7430d0fefc3d40464b7b1131f9ee6d49d4f7d69

input: touchscreen: sec_ts: enable pressure reporting

Bug: 74216515
Change-Id: I8894e8dbcb586f0f45782d97c8657f07b64d1abe

drivers: drm: msm: reset finger mask state on screen off

Change-Id: I943328edf0e946a988865edeb037968a45fe947f

drivers: leds: maxing out the flashlight brightness
- torch have low brightness which is in flashlight_current[0], changing it to flashlight_current[4] and make the current match in dts
- the flash in camera use full brightness hence it doesnt affect in any ways

Signed-off-by: eun0115 <gianpaoloestacio5@gmail.com>

defconfig: Enable fs-verity

Change-Id: Ide2c1520f189d3209eba5d57c56754a99044c0ce